# Uygulama
spring.application.name=waffle-card
server.port=${PORT:8080}

# PostgreSQL - local varsayılan; bulutta env ile override edilir
# Eğer Render veri tabanı sayfasında kullanıcı adı ve şifre değişkenleri de varsa bunları da ekle:
spring.datasource.url=${DATABASE_URL}
# Veri tabanına hangi şemayı kullanacağını açıkça söylüyoruz
spring.jpa.properties.hibernate.default_schema=waffleschema
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Şema yoksa oluştur
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema-init.sql

# JWT - production'da mutlaka JWT_SECRET env kullanın
jwt.secret=${JWT_SECRET:waffleKartGizliAnahtar2024SuperGucluBirAnahtar123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}
