# Uygulama
spring.application.name=waffle-card
server.port=${PORT:8080}

# PostgreSQL - local varsayılan; bulutta env ile override edilir
# Eğer Render veri tabanı sayfasında kullanıcı adı ve şifre değişkenleri de varsa bunları da ekle:
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1234}

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Şema yoksa oluştur
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema-init.sql

# JWT - production'da mutlaka JWT_SECRET env kullanın
jwt.secret=${JWT_SECRET:waffleKartGizliAnahtar2024SuperGucluBirAnahtar123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}
